# Generated by Django 2.1 on 2019-01-13 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=6)),
                ('student_name', models.CharField(max_length=50)),
                ('book_id', models.CharField(max_length=30)),
                ('book_name', models.CharField(max_length=50)),
                ('issue_date', models.DateTimeField(default=datetime.datetime(2019, 1, 13, 17, 13, 23, 860529))),
            ],
        ),
    ]
