# Generated by Django 2.1 on 2019-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=6)),
                ('student_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
